Performing system checks...

System check identified no issues (0 silenced).
March 31, 2019 - 09:18:25
Django version 2.1.7, using settings 'MedusaII.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.
2019-03-31 09:19:06,153 escola.views 8220 INFO     views:index; user_id: 1
2019-03-31 09:19:06,156 escola.views 8220 INFO     views:index; user_id: 1 é aluno.
2019-03-31 09:19:06,156 escola.views 8220 INFO     Lembre-se de retirar as tarefas daqui e generalizar;
2019-03-31 09:19:06,160 escola.views 8220 DEBUG    Encontrei 1 tarefas.
2019-03-31 09:19:06,161 escola.views 8220 INFO     Antes de renderizar a view index, user: 1
2019-03-31 09:19:06,553 escola.models 8220 DEBUG    horario:get_horario()
2019-03-31 09:19:06,555 escola.models 8220 INFO     Puxou 3 turno(s) do banco de dados.
2019-03-31 09:19:06,555 escola.models 8220 INFO     Preparando para entrar no loop de turnos...
2019-03-31 09:19:06,555 escola.models 8220 DEBUG    Turno id:1
2019-03-31 09:19:06,563 escola.models 8220 DEBUG    Turno id:3
2019-03-31 09:19:06,573 escola.models 8220 DEBUG    Turno id:2
2019-03-31 09:29:15,792 escola.views 8220 INFO     views:index; user_id: 1
2019-03-31 09:29:15,796 escola.views 8220 INFO     views:index; user_id: 1 é aluno.
2019-03-31 09:29:15,796 escola.views 8220 INFO     Lembre-se de retirar as tarefas daqui e generalizar;
2019-03-31 09:29:15,798 escola.views 8220 DEBUG    Encontrei 1 tarefas.
2019-03-31 09:29:15,800 escola.views 8220 INFO     Antes de renderizar a view index, user: 1
2019-03-31 09:29:15,822 escola.models 8220 DEBUG    horario:get_horario()
2019-03-31 09:29:15,824 escola.models 8220 INFO     Puxou 3 turno(s) do banco de dados.
2019-03-31 09:29:15,824 escola.models 8220 INFO     Preparando para entrar no loop de turnos...
2019-03-31 09:29:15,824 escola.models 8220 DEBUG    Turno id:1
2019-03-31 09:29:15,833 escola.models 8220 DEBUG    Turno id:3
2019-03-31 09:29:15,845 escola.models 8220 DEBUG    Turno id:2
Performing system checks...

System check identified no issues (0 silenced).
March 31, 2019 - 10:50:37
Django version 2.1.7, using settings 'MedusaII.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x044E35D0>
Traceback (most recent call last):
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\management\base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\management\base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\checks\registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\urls\resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\urls\resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Programação\Medusa II\.vEnv\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Programação\Medusa II\MedusaII\urls.py", line 30, in <module>
    path('', include('escola.urls')),
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Programação\Medusa II\.vEnv\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Programação\Medusa II\escola\urls.py", line 13, in <module>
    from . import views
  File "C:\Programação\Medusa II\escola\views.py", line 62, in <module>
    class NotificacaoListView(ListView):
  File "C:\Programação\Medusa II\escola\views.py", line 64, in NotificacaoListView
    queryset = Notificacao.objects.filter(user=r)
NameError: name 'r' is not defined
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x044E3660>
Traceback (most recent call last):
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\management\base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\management\base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\checks\registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\urls\resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\urls\resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Programação\Medusa II\.vEnv\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Programação\Medusa II\MedusaII\urls.py", line 30, in <module>
    path('', include('escola.urls')),
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Programação\Medusa II\.vEnv\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Programação\Medusa II\escola\urls.py", line 13, in <module>
    from . import views
  File "C:\Programação\Medusa II\escola\views.py", line 69
    
    ^
SyntaxError: unexpected EOF while parsing
Performing system checks...

System check identified no issues (0 silenced).
March 31, 2019 - 10:56:50
Django version 2.1.7, using settings 'MedusaII.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x044E3618>
Traceback (most recent call last):
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\management\base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\management\base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\checks\registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\urls\resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\urls\resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Programação\Medusa II\.vEnv\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Programação\Medusa II\MedusaII\urls.py", line 30, in <module>
    path('', include('escola.urls')),
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Programação\Medusa II\.vEnv\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Programação\Medusa II\escola\urls.py", line 13, in <module>
    from . import views
  File "C:\Programação\Medusa II\escola\views.py", line 69
    return Notificacao.objects.filter(user=self.request.)
                                                        ^
SyntaxError: invalid syntax
Performing system checks...

System check identified no issues (0 silenced).
March 31, 2019 - 10:59:38
Django version 2.1.7, using settings 'MedusaII.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).
March 31, 2019 - 11:02:48
Django version 2.1.7, using settings 'MedusaII.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.
2019-03-31 11:02:52,837 escola.views 22244 INFO     views:index; user_id: 1
2019-03-31 11:02:52,840 escola.views 22244 INFO     views:index; user_id: 1 é aluno.
2019-03-31 11:02:52,840 escola.views 22244 INFO     Lembre-se de retirar as tarefas daqui e generalizar;
2019-03-31 11:02:52,843 escola.views 22244 DEBUG    Encontrei 1 tarefas.
2019-03-31 11:02:52,844 escola.views 22244 INFO     Antes de renderizar a view index, user: 1
2019-03-31 11:02:53,273 escola.models 22244 DEBUG    horario:get_horario()
2019-03-31 11:02:53,275 escola.models 22244 INFO     Puxou 3 turno(s) do banco de dados.
2019-03-31 11:02:53,275 escola.models 22244 INFO     Preparando para entrar no loop de turnos...
2019-03-31 11:02:53,275 escola.models 22244 DEBUG    Turno id:1
2019-03-31 11:02:53,285 escola.models 22244 DEBUG    Turno id:3
2019-03-31 11:02:53,293 escola.models 22244 DEBUG    Turno id:2
2019-03-31 11:03:01,877 django.request 22244 ERROR    Internal Server Error: /notificacoes
Traceback (most recent call last):
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\handlers\base.py", line 154, in _get_response
    response = response.render()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: TEMPLATE_NAME, escola/notificacao_list.html
2019-03-31 11:03:01,888 django.server 22244 ERROR    "GET /notificacoes HTTP/1.1" 500 97143
Performing system checks...

System check identified no issues (0 silenced).
March 31, 2019 - 11:05:33
Django version 2.1.7, using settings 'MedusaII.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.
2019-03-31 11:05:37,104 django.request 22184 ERROR    Internal Server Error: /notificacoes
Traceback (most recent call last):
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\handlers\base.py", line 154, in _get_response
    response = response.render()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 26: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2019-03-31 11:05:37,115 django.server 22184 ERROR    "GET /notificacoes HTTP/1.1" 500 161346
2019-03-31 11:05:44,985 django.request 22184 ERROR    Internal Server Error: /notificacoes
Traceback (most recent call last):
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\handlers\base.py", line 154, in _get_response
    response = response.render()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 26: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2019-03-31 11:05:44,990 django.server 22184 ERROR    "GET /notificacoes HTTP/1.1" 500 161712
Performing system checks...

System check identified no issues (0 silenced).
March 31, 2019 - 11:06:31
Django version 2.1.7, using settings 'MedusaII.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).
March 31, 2019 - 11:07:21
Django version 2.1.7, using settings 'MedusaII.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).
March 31, 2019 - 11:08:24
Django version 2.1.7, using settings 'MedusaII.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).
March 31, 2019 - 11:12:09
Django version 2.1.7, using settings 'MedusaII.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.
2019-03-31 11:19:56,093 django.request 20924 ERROR    Internal Server Error: /notificacoes
Traceback (most recent call last):
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: '!noti.visualizado'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\handlers\base.py", line 154, in _get_response
    response = response.render()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\defaulttags.py", line 810, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\defaulttags.py", line 950, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\defaulttags.py", line 883, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\defaulttags.py", line 886, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\template\base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '!noti.visualizado' from '!noti.visualizado'
2019-03-31 11:19:56,108 django.server 20924 ERROR    "GET /notificacoes HTTP/1.1" 500 204918
2019-03-31 11:20:15,435 django.request 22744 WARNING  Not Found: /favicon.ico
2019-03-31 11:20:15,444 django.server 22744 WARNING  "GET /favicon.ico HTTP/1.1" 404 10078
2019-03-31 11:20:26,212 escola.views 20924 INFO     views:index; user_id: 1
2019-03-31 11:20:26,219 escola.views 20924 INFO     views:index; user_id: 1 é aluno.
2019-03-31 11:20:26,219 escola.views 20924 INFO     Lembre-se de retirar as tarefas daqui e generalizar;
2019-03-31 11:20:26,224 escola.views 20924 DEBUG    Encontrei 1 tarefas.
2019-03-31 11:20:26,225 escola.views 20924 INFO     Antes de renderizar a view index, user: 1
2019-03-31 11:20:26,240 escola.models 20924 DEBUG    horario:get_horario()
2019-03-31 11:20:26,242 escola.models 20924 INFO     Puxou 3 turno(s) do banco de dados.
2019-03-31 11:20:26,242 escola.models 20924 INFO     Preparando para entrar no loop de turnos...
2019-03-31 11:20:26,242 escola.models 20924 DEBUG    Turno id:1
2019-03-31 11:20:26,255 escola.models 20924 DEBUG    Turno id:3
2019-03-31 11:20:26,268 escola.models 20924 DEBUG    Turno id:2
2019-03-31 11:20:54,473 escola.views 20924 INFO     views:index; user_id: 1
2019-03-31 11:20:54,476 escola.views 20924 INFO     views:index; user_id: 1 é aluno.
2019-03-31 11:20:54,477 escola.views 20924 INFO     Lembre-se de retirar as tarefas daqui e generalizar;
2019-03-31 11:20:54,480 escola.views 20924 DEBUG    Encontrei 1 tarefas.
2019-03-31 11:20:54,481 escola.views 20924 INFO     Antes de renderizar a view index, user: 1
2019-03-31 11:20:54,502 escola.models 20924 DEBUG    horario:get_horario()
2019-03-31 11:20:54,503 escola.models 20924 INFO     Puxou 3 turno(s) do banco de dados.
2019-03-31 11:20:54,503 escola.models 20924 INFO     Preparando para entrar no loop de turnos...
2019-03-31 11:20:54,504 escola.models 20924 DEBUG    Turno id:1
2019-03-31 11:20:54,512 escola.models 20924 DEBUG    Turno id:3
2019-03-31 11:20:54,524 escola.models 20924 DEBUG    Turno id:2
2019-03-31 11:21:51,689 escola.views 20924 INFO     views:index; user_id: 1
2019-03-31 11:21:51,695 escola.views 20924 INFO     views:index; user_id: 1 é aluno.
2019-03-31 11:21:51,695 escola.views 20924 INFO     Lembre-se de retirar as tarefas daqui e generalizar;
2019-03-31 11:21:51,698 escola.views 20924 DEBUG    Encontrei 1 tarefas.
2019-03-31 11:21:51,699 escola.views 20924 INFO     Antes de renderizar a view index, user: 1
2019-03-31 11:21:51,717 escola.models 20924 DEBUG    horario:get_horario()
2019-03-31 11:21:51,719 escola.models 20924 INFO     Puxou 3 turno(s) do banco de dados.
2019-03-31 11:21:51,719 escola.models 20924 INFO     Preparando para entrar no loop de turnos...
2019-03-31 11:21:51,719 escola.models 20924 DEBUG    Turno id:1
2019-03-31 11:21:51,734 escola.models 20924 DEBUG    Turno id:3
2019-03-31 11:21:51,746 escola.models 20924 DEBUG    Turno id:2
2019-03-31 11:22:29,295 escola.views 20924 INFO     views:index; user_id: 1
2019-03-31 11:22:29,299 escola.views 20924 INFO     views:index; user_id: 1 é aluno.
2019-03-31 11:22:29,300 escola.views 20924 INFO     Lembre-se de retirar as tarefas daqui e generalizar;
2019-03-31 11:22:29,303 escola.views 20924 DEBUG    Encontrei 1 tarefas.
2019-03-31 11:22:29,304 escola.views 20924 INFO     Antes de renderizar a view index, user: 1
2019-03-31 11:22:29,320 escola.models 20924 DEBUG    horario:get_horario()
2019-03-31 11:22:29,321 escola.models 20924 INFO     Puxou 3 turno(s) do banco de dados.
2019-03-31 11:22:29,321 escola.models 20924 INFO     Preparando para entrar no loop de turnos...
2019-03-31 11:22:29,322 escola.models 20924 DEBUG    Turno id:1
2019-03-31 11:22:29,332 escola.models 20924 DEBUG    Turno id:3
2019-03-31 11:22:29,342 escola.models 20924 DEBUG    Turno id:2
2019-03-31 11:22:40,298 escola.views 20924 INFO     views:index; user_id: 1
2019-03-31 11:22:40,304 escola.views 20924 INFO     views:index; user_id: 1 é aluno.
2019-03-31 11:22:40,304 escola.views 20924 INFO     Lembre-se de retirar as tarefas daqui e generalizar;
2019-03-31 11:22:40,307 escola.views 20924 DEBUG    Encontrei 1 tarefas.
2019-03-31 11:22:40,308 escola.views 20924 INFO     Antes de renderizar a view index, user: 1
2019-03-31 11:22:40,322 escola.models 20924 DEBUG    horario:get_horario()
2019-03-31 11:22:40,324 escola.models 20924 INFO     Puxou 3 turno(s) do banco de dados.
2019-03-31 11:22:40,324 escola.models 20924 INFO     Preparando para entrar no loop de turnos...
2019-03-31 11:22:40,324 escola.models 20924 DEBUG    Turno id:1
2019-03-31 11:22:40,334 escola.models 20924 DEBUG    Turno id:3
2019-03-31 11:22:40,346 escola.models 20924 DEBUG    Turno id:2
----------------------------------------
Exception happened during processing of request from ('10.0.0.101', 44254)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




Exception happened during processing of request fromException happened during processing of request fromException happened during processing of request fromException happened during processing of request fromException happened during processing of request from     ('10.0.0.101', 44280)('10.0.0.101', 44252)('10.0.0.101', 44278)('10.0.0.101', 44276)('10.0.0.101', 44274)




Traceback (most recent call last):
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
Traceback (most recent call last):
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
Traceback (most recent call last):
Traceback (most recent call last):
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 717, in __init__
    self.handle()
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 717, in __init__
    self.handle()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
Traceback (most recent call last):
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\servers\basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\servers\basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 717, in __init__
    self.handle()
Traceback (most recent call last):
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 717, in __init__
    self.handle()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\servers\basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\servers\basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
--------------------------------------------------------------------------------

  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 717, in __init__
    self.handle()
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\servers\basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
----------------------------------------  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socketserver.py", line 717, in __init__
    self.handle()

ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
--------------------------------------------------------------------------------  File "C:\Programação\Medusa II\.vEnv\lib\site-packages\django\core\servers\basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)


  File "c:\users\wwwvi\appdata\local\programs\python\python37-32\Lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
----------------------------------------
Performing system checks...

System check identified no issues (0 silenced).
March 31, 2019 - 11:24:48
Django version 2.1.7, using settings 'MedusaII.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.
